modLoader="javafml"
loaderVersion="[47,)"
license="CC.BY.SA.4.0"

[[mods]]
modId="oldcraftallow"
version="1.2.5"
displayName="oldcraftallow"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://modrinth.com/datapack/oldcraftallow"
authors="KuYu,"

[[dependencies.oldcraftallow]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.oldcraftallow]]
    modId="bookshelf"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.oldcraftallow]]
    modId="architectury"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.oldcraftallow]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.oldcraftallow]]
    modId="architectury"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

